  apiVersion: v1
  kind: Service
  metadata:
    name: ams-service
  spec:
    selector:
      app: amsproject
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 80
        targetPort: 5000
        nodePort: 32310